### ISSUE TITLE
Images use too many storage

### ISSUE THREAD

**Issue by sabit990928** [editor-js/simple-image#17]
Maybe I'm wrong, but when I use simpleImage and set 4-6 images to my editor, my backend requests spent too many time to fetch data

There is Express(Node JS) for backend and MongoDB as database

**Comment by neSpecc** [comment]
Try to use [Image](http://github.com/editor-js/image) tool instead of Simple Image

**Comment by sabit990928** [comment]
Yeah, I see it. As I know you also a contributor to this library. 

There is will be several questions about implementation of image library)
